### ISSUE TITLE
Scroll icons not showing

### ISSUE THREAD

**Issue by CaidenKehrer** [darkcharl/secret-scrolls#6]
Icons for scrolls are not showing. I have attached a screenshot showing this example. 

Playing on Patch 7. 

![image](https://github.com/user-attachments/assets/2dc5c56e-1283-4028-9817-55ef3e701517)

**Comment by fhare666** [comment]
Second, also not working for me.

**Comment by darkcharl** [comment]
Thanks for the heads up! This is essentially a duplicate of #7, if you would like to follow progress subscribe to that issue! I'm going to mark this as duplicate in the interim.

**Comment by darkcharl** [comment]
Closing as duplicate. Please follow #7!
