### ISSUE TITLE
Mod won't update, and the scroll icons show blank in inventory

### ISSUE THREAD

**Issue by Colcobau** [darkcharl/secret-scrolls#7]
Hi!

I updated my mods today, and for some reason, this is the only mod that won't actually update (Despite the Mod Manager saying it updated), and for some reason, the icons for the scrolls from this mod show blank on inventory as well as on merchant's stock and chests. Attached are screenshots.

![IMG_1881](https://github.com/user-attachments/assets/986a4428-732f-4864-8bc0-c785c8e9acdf)
![IMG_1882](https://github.com/user-attachments/assets/77beac6a-c9b3-48a1-b729-2f270ee9ce31)

Already tried uninstalling and re-installing the mod to no avail.

Any ideas?

Thanks!

**Comment by fhare666** [comment]
I second this, also not working for me.

**Comment by PollastreGH** [comment]
I third this, I'm getting both of those errors on my end

**Comment by Derisat** [comment]
Came here to report this as well.

**Comment by darkcharl** [comment]
Thanks for reporting! 

I'm going to take a look, this is likely due to the mod format changes of Patch 7 that the mod has not been updated for yet.
